FROM node:alpine
LABEL maintainer="rashley-iqt <rashley@iqt.org>"

RUN apk update && apk add git
RUN git config --global user.email "rashley@iqt.org"
RUN git config --global user.name "rashley-iqt"

COPY . /app
WORKDIR /app
RUN sed -i '2i\
  "homepage": "https:\/\/cyberreboot.github.io\/CRviz", \
' package.json

RUN npm i npm@latest -g
RUN npm install --no-optional
RUN npm run build
CMD npm run deploy
