FROM node:alpine
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

RUN apk update && apk add git yarn
RUN git config --global user.email "clewis@iqt.org"
RUN git config --global user.name "Charlie Lewis"

COPY . /app
WORKDIR /app
RUN sed -i '2i\
  "homepage": "https:\/\/cyberreboot.github.io\/CRviz", \
' package.json

RUN npm i npm@latest -g
RUN npm install --no-optional
RUN yarn run build
CMD yarn run deploy
